### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by 3kh0** [Kidatschool/GoogleSiteHTMLGames#1]
Hello there!

I was just questioning what you are trying to do with my code. You had withdrawn my name from it so I assume you are not trying to develop it. This was code that I got and it could land you in some legal problems if you try and steal it. I am awaiting your response.

Echo

**Comment by Kidatschool** [comment]
Hello!

Yeah, there's no development of any type going on, just me messing around with GitHub and HTML lol. I'm fairly new to coding and GitHub so I was just messing around with different things to see what I could create. Hopefully this answers your question and I don't have to worry about any of those legal problems you mentioned.

**Comment by Kidatschool** [comment]
Also, I forgot to mention if you have any issues with me using your code please tell me, as this is just an account I mess around on and I want to avoid any problems with actual creators. thanks and sorry for any confusion

**Comment by 3kh0** [comment]
> Hello!
> 
> Yeah, there's no development of any type going on, just me messing around with GitHub and HTML lol. I'm fairly new to coding and GitHub so I was just messing around with different things to see what I could create. Hopefully this answers your question and I don't have to worry about any of those legal problems you mentioned.

ok thank you for your reply, can you please remove my projects from your site as well as any other projects by other developers. Thanks!
